name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
    - run: docker run -e CI=true cygnetops/react-test npm test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16-alpine'

    - name: Build React App
      run: |
        npm install
        npm run build

    - name: Package for Elastic Beanstalk
      run: zip -r deploy.zip . -x '*.git*'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: dockerenv
        environment_name: Dockerenv-env
        existing_bucket_name: elasticbeanstalk-us-east-1-829110048242
        version_label: "version-${{ github.run_number }}-${{ github.sha }}"
        version_description: none
        region: us-east-1
        deployment_package: deploy.zip
